"""
Agent Factory — generates new agents dynamically.

With ANTHROPIC_API_KEY: each agent gets a fully LLM-generated persona
(background, expertise, personality, and optionally a hidden agenda).

Without ANTHROPIC_API_KEY: falls back to procedural generation using
pre-defined building blocks — still produces varied plausible profiles.

The factory also supports spawning adversarial agent clusters for the
security test scenarios (Sybil, capture, collusion).
"""
from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import random
import string
from dataclasses import dataclass, field
from typing import Literal

import httpx

from .config import (
    ANTHROPIC_API_KEY, ANTHROPIC_MODEL, LLM_ENABLED,
    TEST_ORG_DORMAINS,
)

log = logging.getLogger(__name__)


# ── Agent profile ─────────────────────────────────────────────────────────────

AgentIntent = Literal["genuine", "sybil", "capture", "collusion", "passive"]


@dataclass
class AgentProfile:
    """
    Full profile for one agent. Generated by LLM or procedurally.
    The 'intent' field is known only to the factory and the agent — not
    submitted to the system. It shapes the agent's decision-making.
    """
    handle: str
    display_name: str
    email: str
    password: str

    # Persona narrative (LLM-generated or template)
    background: str
    personality: str          # how they communicate
    expertise_summary: str    # what they claim to know

    # Behavioural parameters (0.0–1.0)
    dormain_weights: dict[str, float]   # which dormains they engage with
    curiosities:     dict[str, float]   # curiosity signals to declare

    activity_level: float = 0.5         # 0=very passive, 1=very active
    post_frequency: float = 0.4
    vote_frequency: float = 0.6
    review_frequency: float = 0.3
    sponsor_frequency: float = 0.1
    stf_diligence: float = 0.8          # probability of filing verdict when assigned

    # Secret intent — shapes adversarial behaviour
    intent: AgentIntent = "genuine"
    target_dormain: str | None = None   # for capture/sybil: which dormain to push
    coalition_id: str | None = None     # shared among colluding agents

    # Style for LLM prompting
    writing_style: str = "thoughtful"   # thoughtful | assertive | questioning | terse


# ── LLM caller ───────────────────────────────────────────────────────────────

async def _call_claude(prompt: str, system: str = "", max_tokens: int = 800) -> str | None:
    if not LLM_ENABLED:
        return None
    try:
        async with httpx.AsyncClient(timeout=30) as client:
            r = await client.post(
                "https://api.anthropic.com/v1/messages",
                headers={
                    "x-api-key": ANTHROPIC_API_KEY,
                    "anthropic-version": "2023-06-01",
                    "content-type": "application/json",
                },
                json={
                    "model": ANTHROPIC_MODEL,
                    "max_tokens": max_tokens,
                    "system": system or (
                        "You are generating test personas for a governance simulation. "
                        "Respond only with the requested JSON. No markdown, no explanation."
                    ),
                    "messages": [{"role": "user", "content": prompt}],
                },
            )
            if r.status_code != 200:
                log.warning(f"Claude API {r.status_code}: {r.text[:100]}")
                return None
            data = r.json()
            return data["content"][0]["text"].strip()
    except Exception as e:
        log.warning(f"Claude API error: {e}")
        return None


# ── Handle / password generation ─────────────────────────────────────────────

_ADJECTIVES = [
    "swift", "careful", "bold", "quiet", "sharp", "deep", "clear", "open",
    "steady", "bright", "keen", "warm", "just", "free", "fair", "wise",
]
_NOUNS = [
    "voice", "lens", "node", "path", "hand", "mind", "eye", "root",
    "thread", "chain", "frame", "bridge", "shore", "field", "stone", "wave",
]


def _make_handle(seed: str) -> str:
    h = hashlib.sha256(seed.encode()).hexdigest()
    adj  = _ADJECTIVES[int(h[0:2], 16) % len(_ADJECTIVES)]
    noun = _NOUNS[int(h[2:4], 16) % len(_NOUNS)]
    num  = int(h[4:6], 16) % 100
    return f"{adj}_{noun}_{num:02d}"


def _make_password(handle: str) -> str:
    h = hashlib.sha256(f"agent-{handle}-orbsys".encode()).hexdigest()[:16]
    return f"ag-{h}"


# ── Procedural fallback ────────────────────────────────────────────────────────

_BACKGROUNDS = [
    "Software engineer with 8 years in distributed systems. Recently moved into"
    " governance research after a stint at a DAO that failed spectacularly.",

    "Academic researcher focused on collective intelligence and deliberative democracy."
    " Joining to study how digital governance systems perform under load.",

    "Former policy analyst, now building community governance tooling. Interested in"
    " how competence metrics interact with traditional democratic legitimacy.",

    "Security researcher. Primary interest is auditing how the aSTF mechanism holds"
    " up against coordinated adversarial behaviour.",

    "Treasury professional with background in cooperative finance. Sceptical of"
    " token-weighted systems; cautiously optimistic about competence-based alternatives.",

    "Open-source maintainer burned out by BDFL governance. Looking for a structured"
    " alternative that preserves meritocracy without concentrating power.",

    "PhD student in political science studying digital polycentrism. Using this org"
    " as a live case study for their dissertation.",

    "Engineer turned governance practitioner. Has implemented Holacracy and found it"
    " lacking in conflict resolution mechanisms. Testing PAAS as an alternative.",
]

_PERSONALITIES = [
    "Methodical and data-driven. Rarely posts without citing evidence. Can come across"
    " as cold but their contributions are usually substantive.",

    "Warm and community-oriented. Tends to summarise group positions and draw out"
    " quieter voices. Not always technically deep but socially skilled.",

    "Skeptical and questioning. Challenges assumptions, sometimes frustratingly."
    " Improves decisions when they engage but can stall consensus.",

    "Direct and concise. Short posts, clear positions. Sometimes perceived as brusque.",

    "Deliberative and long-form. Writes carefully reasoned arguments. High signal"
    " but low volume — only posts when they have something important to say.",

    "Enthusiastic and high-volume. Posts frequently, sometimes before thinking through"
    " all implications. Usually corrects course when challenged.",
]

_STYLES = ["thoughtful", "assertive", "questioning", "terse", "deliberative", "concise"]

_DORMAIN_NAMES = [d["name"] for d in TEST_ORG_DORMAINS]


def _procedural_profile(seed: str, intent: AgentIntent = "genuine",
                         target_dormain: str | None = None,
                         coalition_id: str | None = None) -> AgentProfile:
    h   = hashlib.sha256(seed.encode()).hexdigest()
    rng = random.Random(int(h, 16))

    handle   = _make_handle(seed)
    password = _make_password(handle)

    # Pick 1–3 primary dormains
    num_dormains = rng.randint(1, 3)
    primary_dormains = rng.sample(_DORMAIN_NAMES, num_dormains)
    if target_dormain and target_dormain not in primary_dormains:
        primary_dormains = [target_dormain] + primary_dormains[:num_dormains - 1]

    dormain_weights: dict[str, float] = {}
    for d in _DORMAIN_NAMES:
        if d in primary_dormains:
            dormain_weights[d] = round(rng.uniform(0.55, 0.95), 2)
        else:
            dormain_weights[d] = round(rng.uniform(0.05, 0.30), 2)

    curiosities: dict[str, float] = {}
    for d, w in dormain_weights.items():
        if rng.random() < 0.7:  # only declare curiosities for some domains
            curiosities[d] = round(min(1.0, w + rng.gauss(0.05, 0.1)), 2)

    activity = rng.betavariate(2, 3)  # right-skewed — most agents are somewhat passive

    # Adversarial agents are more active (they have an agenda)
    if intent in ("sybil", "capture", "collusion"):
        activity = max(activity, rng.uniform(0.55, 0.85))

    background  = rng.choice(_BACKGROUNDS)
    personality = rng.choice(_PERSONALITIES)
    style       = rng.choice(_STYLES)

    # Build display name
    first_names = ["Alex", "Jordan", "Morgan", "Casey", "Riley", "Avery",
                   "Quinn", "Reese", "Cameron", "Sage", "Blair", "Hayden",
                   "Emery", "Finley", "Rowan", "Skyler", "Dakota", "River"]
    last_initials = list("ABCDEFGHJKLMNPRSTW")
    display_name = f"{rng.choice(first_names)} {rng.choice(last_initials)}."

    return AgentProfile(
        handle=handle,
        display_name=display_name,
        email=f"{handle}@sim.orbsys.test",
        password=password,
        background=background,
        personality=personality,
        expertise_summary=f"Primary expertise in {', '.join(primary_dormains)}.",
        dormain_weights=dormain_weights,
        curiosities=curiosities,
        activity_level=round(activity, 2),
        post_frequency=round(rng.gauss(0.45, 0.15), 2),
        vote_frequency=round(rng.gauss(0.65, 0.15), 2),
        review_frequency=round(rng.gauss(0.30, 0.12), 2),
        sponsor_frequency=round(rng.gauss(0.12, 0.08), 2),
        stf_diligence=round(rng.gauss(0.80, 0.12), 2),
        intent=intent,
        target_dormain=target_dormain,
        coalition_id=coalition_id,
        writing_style=style,
    )


# ── LLM-based profile generation ─────────────────────────────────────────────

async def _llm_profile(seed: str, intent: AgentIntent = "genuine",
                        target_dormain: str | None = None,
                        coalition_id: str | None = None) -> AgentProfile:
    """
    Generate a realistic persona via Claude. Falls back to procedural on failure.
    The hidden agenda (intent) is reflected in the persona's goals but not
    explicitly flagged in the JSON — the system can't see it.
    """
    dormain_list = ", ".join(_DORMAIN_NAMES)

    intent_hint = ""
    if intent == "sybil":
        intent_hint = (
            f"This person has a specific agenda: they want to push governance decisions "
            f"that favour the '{target_dormain or 'Governance'}' domain. They are part of "
            f"a coordinated group but won't admit this. Their persona should be plausible "
            f"and not obviously adversarial."
        )
    elif intent == "capture":
        intent_hint = (
            f"This person is strategically trying to build their W_s in "
            f"'{target_dormain or 'Governance'}' and get into that circle. "
            f"They appear genuinely interested but are methodical about it."
        )
    elif intent == "collusion":
        intent_hint = (
            f"This person is part of a mutual-endorsement network. They will endorse "
            f"their coalition members' contributions highly. They appear genuine."
        )

    prompt = f"""Generate a realistic member persona for a governance simulation testing the 
PAAS (Polycentric Autonomy-Audit System) framework. The org has these knowledge domains: {dormain_list}.

{intent_hint}

Return ONLY a JSON object with these exact fields:
{{
  "display_name": "First L.",
  "background": "2-3 sentences about professional background and why they joined",
  "personality": "1-2 sentences about communication style",  
  "expertise_summary": "1 sentence",
  "primary_dormains": ["list", "of", "1-3", "domain names from: {dormain_list}"],
  "writing_style": "one of: thoughtful | assertive | questioning | terse | deliberative",
  "activity_level": 0.0-1.0,
  "post_frequency": 0.0-1.0,
  "vote_frequency": 0.0-1.0,
  "review_frequency": 0.0-1.0
}}"""

    raw = await _call_claude(prompt)
    if not raw:
        return _procedural_profile(seed, intent, target_dormain, coalition_id)

    try:
        # Strip any markdown fences
        clean = raw.strip()
        if clean.startswith("```"):
            clean = clean.split("\n", 1)[1].rsplit("```", 1)[0].strip()
        data = json.loads(clean)

        handle   = _make_handle(seed)
        password = _make_password(handle)

        primary = [d for d in data.get("primary_dormains", []) if d in _DORMAIN_NAMES]
        if not primary:
            primary = [_DORMAIN_NAMES[0]]

        rng = random.Random(int(hashlib.sha256(seed.encode()).hexdigest(), 16))
        dormain_weights: dict[str, float] = {}
        for d in _DORMAIN_NAMES:
            if d in primary:
                dormain_weights[d] = round(rng.uniform(0.6, 0.95), 2)
            else:
                dormain_weights[d] = round(rng.uniform(0.05, 0.25), 2)

        curiosities = {d: round(min(1.0, w + 0.05), 2)
                       for d, w in dormain_weights.items()
                       if w > 0.4 and rng.random() < 0.75}

        return AgentProfile(
            handle=handle,
            display_name=data.get("display_name", "Agent U."),
            email=f"{handle}@sim.orbsys.test",
            password=password,
            background=data.get("background", ""),
            personality=data.get("personality", ""),
            expertise_summary=data.get("expertise_summary", ""),
            dormain_weights=dormain_weights,
            curiosities=curiosities,
            activity_level=float(data.get("activity_level", 0.5)),
            post_frequency=float(data.get("post_frequency", 0.4)),
            vote_frequency=float(data.get("vote_frequency", 0.6)),
            review_frequency=float(data.get("review_frequency", 0.3)),
            sponsor_frequency=float(data.get("sponsor_frequency", 0.1)),
            stf_diligence=float(data.get("stf_diligence", 0.8)),
            intent=intent,
            target_dormain=target_dormain,
            coalition_id=coalition_id,
            writing_style=data.get("writing_style", "thoughtful"),
        )
    except (json.JSONDecodeError, KeyError, ValueError) as e:
        log.debug(f"LLM profile parse error: {e} — falling back to procedural")
        return _procedural_profile(seed, intent, target_dormain, coalition_id)


# ── Public factory API ────────────────────────────────────────────────────────

class AgentFactory:
    """
    Generates agent profiles on demand — genuine and adversarial.
    Tracks issued handles to prevent duplicates.
    """

    def __init__(self):
        self._issued: set[str] = set()
        self._counter = 0

    def _next_seed(self, prefix: str = "") -> str:
        self._counter += 1
        return f"{prefix}-{self._counter}-{''.join(random.choices(string.ascii_lowercase, k=6))}"

    async def spawn_genuine(self, n: int = 1) -> list[AgentProfile]:
        """Generate n genuine, diverse agent profiles."""
        profiles = []
        for _ in range(n):
            seed = self._next_seed("genuine")
            p = await _llm_profile(seed) if LLM_ENABLED else _procedural_profile(seed)
            while p.handle in self._issued:
                seed = self._next_seed("genuine-retry")
                p = await _llm_profile(seed) if LLM_ENABLED else _procedural_profile(seed)
            self._issued.add(p.handle)
            profiles.append(p)
        return profiles

    async def spawn_sybil_cluster(
        self, n: int, target_dormain: str | None = None
    ) -> list[AgentProfile]:
        """Generate n Sybil agents sharing a hidden agenda."""
        coalition = f"sybil-{random.randint(1000, 9999)}"
        dormain   = target_dormain or random.choice(_DORMAIN_NAMES)
        profiles  = []
        tasks = [
            _llm_profile(self._next_seed("sybil"), "sybil", dormain, coalition)
            if LLM_ENABLED else
            asyncio.coroutine(
                lambda s=self._next_seed("sybil"): _procedural_profile(s, "sybil", dormain, coalition)
            )()
            for _ in range(n)
        ]
        results = await asyncio.gather(*tasks)
        for p in results:
            if p.handle not in self._issued:
                self._issued.add(p.handle)
                profiles.append(p)
        log.info(f"Spawned Sybil cluster: {n} agents targeting '{dormain}' (coalition={coalition})")
        return profiles

    async def spawn_capture_cluster(
        self, n: int, target_dormain: str | None = None
    ) -> list[AgentProfile]:
        """Generate agents coordinating to capture a specific circle."""
        coalition = f"capture-{random.randint(1000, 9999)}"
        dormain   = target_dormain or random.choice(_DORMAIN_NAMES)
        profiles  = []
        for _ in range(n):
            seed = self._next_seed("capture")
            p = (await _llm_profile(seed, "capture", dormain, coalition)
                 if LLM_ENABLED
                 else _procedural_profile(seed, "capture", dormain, coalition))
            if p.handle not in self._issued:
                self._issued.add(p.handle)
                profiles.append(p)
        log.info(f"Spawned capture cluster: {n} agents targeting '{dormain}'")
        return profiles

    async def spawn_collusion_ring(self, n: int) -> list[AgentProfile]:
        """Generate a mutual-endorsement colluding ring."""
        coalition = f"collude-{random.randint(1000, 9999)}"
        profiles  = []
        for _ in range(n):
            seed = self._next_seed("collude")
            p = (await _llm_profile(seed, "collusion", None, coalition)
                 if LLM_ENABLED
                 else _procedural_profile(seed, "collusion", None, coalition))
            if p.handle not in self._issued:
                self._issued.add(p.handle)
                profiles.append(p)
        log.info(f"Spawned collusion ring: {n} agents (coalition={coalition})")
        return profiles

    async def spawn_batch(
        self,
        total: int,
        genuine_ratio: float = 0.75,
        sybil_ratio: float = 0.10,
        capture_ratio: float = 0.08,
        collusion_ratio: float = 0.07,
    ) -> list[AgentProfile]:
        """
        Spawn a mixed batch — realistic population with embedded adversarial clusters.
        Ratios must sum to ≤1.0.
        """
        n_genuine   = round(total * genuine_ratio)
        n_sybil     = round(total * sybil_ratio)
        n_capture   = round(total * capture_ratio)
        n_collusion = round(total * collusion_ratio)
        # Any remainder goes to genuine
        n_genuine  += total - n_genuine - n_sybil - n_capture - n_collusion

        all_profiles: list[AgentProfile] = []
        # Genuine agents in parallel batches of 10
        for i in range(0, n_genuine, 10):
            batch = await self.spawn_genuine(min(10, n_genuine - i))
            all_profiles.extend(batch)

        if n_sybil > 0:
            all_profiles.extend(await self.spawn_sybil_cluster(n_sybil))
        if n_capture > 0:
            all_profiles.extend(await self.spawn_capture_cluster(n_capture))
        if n_collusion > 0:
            all_profiles.extend(await self.spawn_collusion_ring(n_collusion))

        random.shuffle(all_profiles)
        log.info(
            f"Batch spawned: {len(all_profiles)} total "
            f"(genuine={n_genuine}, sybil={n_sybil}, "
            f"capture={n_capture}, collusion={n_collusion})"
        )
        return all_profiles
